Repository halo-sigs/richtext-editor, pull requests merged in 2023-09, with the labels that each got.

#38 refactor: editor bubble menu and its extensions
  docs/extension.md
  packages/editor/src/components/EditorBubbleMenu.vue
  packages/editor/src/components/bubble/BubbleItem.vue
  packages/editor/src/components/bubble/BubbleMenu.vue
  packages/editor/src/components/bubble/BubbleMenuPlugin.ts
  packages/editor/src/components/index.ts
  packages/editor/src/extensions/audio/AudioView.vue
  packages/editor/src/extensions/audio/BubbleItemAudioLink.vue
  packages/editor/src/extensions/audio/index.ts
  packages/editor/src/extensions/blockquote/index.ts
  packages/editor/src/extensions/bold/index.ts
  packages/editor/src/extensions/code-block/CodeBlockViewRenderer.vue
  packages/editor/src/extensions/code-block/code-block.ts
  packages/editor/src/extensions/code/index.ts
  packages/editor/src/extensions/color/ColorBubbleItem.vue
  packages/editor/src/extensions/color/index.ts
  packages/editor/src/extensions/highlight/HighlightBubbleItem.vue
  packages/editor/src/extensions/highlight/index.ts
  packages/editor/src/extensions/iframe/BubbleItemIframeLink.vue
  packages/editor/src/extensions/iframe/BubbleItemIframeSize.vue
  packages/editor/src/extensions/iframe/IframeView.vue
  packages/editor/src/extensions/iframe/index.ts
  packages/editor/src/extensions/image/BubbleItemImageAlt.vue
  packages/editor/src/extensions/image/BubbleItemImageLink.vue
  packages/editor/src/extensions/image/BubbleItemImageSize.vue
  packages/editor/src/extensions/image/ImageView.vue
  packages/editor/src/extensions/image/index.ts
  packages/editor/src/extensions/index.ts
  packages/editor/src/extensions/italic/index.ts
  packages/editor/src/extensions/link/LinkBubbleButton.vue
  packages/editor/src/extensions/link/index.ts
  packages/editor/src/extensions/strike/index.ts
  packages/editor/src/extensions/subscript/index.ts
  packages/editor/src/extensions/superscript/index.ts
  packages/editor/src/extensions/text-align/index.ts
  packages/editor/src/extensions/text/index.ts
  packages/editor/src/extensions/underline/index.ts
  packages/editor/src/extensions/video/BubbleItemVideoLink.vue
  packages/editor/src/extensions/video/BubbleItemVideoSize.vue
  packages/editor/src/extensions/video/VideoView.vue
  packages/editor/src/extensions/video/index.ts
  packages/editor/src/types/index.ts
  packages/editor/src/utils/delete-node.ts
  packages/editor/src/utils/index.ts
Labels: release-note, kind/improvement, approved, lgtm

#39 refactor: optimize table component
  packages/editor/package.json
  packages/editor/src/extensions/image/BubbleItemImageSize.vue
  packages/editor/src/extensions/table/index.ts
  packages/editor/src/extensions/table/table-cell.ts
  packages/editor/src/extensions/table/table-header.ts
  packages/editor/src/extensions/table/table-row.ts
  packages/editor/src/extensions/table/util.ts
  packages/editor/src/extensions/text/index.ts
  packages/editor/src/locales/en.yaml
  packages/editor/src/locales/zh-CN.yaml
  packages/editor/src/styles/base.scss
  packages/editor/src/styles/index.scss
  packages/editor/src/styles/table.scss
  pnpm-lock.yaml
Labels: kind/feature, release-note, approved, lgtm

#43 chore: using the mod-a shortcut key in the code block will only select the code
  packages/editor/src/extensions/code-block/code-block.ts
Labels: release-note, kind/improvement, approved, lgtm

#41 fix: solve the command menu scrolling issue
  packages/editor/package.json
  packages/editor/src/extensions/commands-menu/CommandsView.vue
  packages/editor/src/extensions/commands-menu/commands.ts
  pnpm-lock.yaml
Labels: kind/bug, release-note, approved, lgtm

#47 fix: resolve the issue of not maintaining aspect ratio when dragging images
  packages/editor/src/extensions/image/BubbleItemImageSize.vue
  packages/editor/src/extensions/image/ImageView.vue
Labels: kind/bug, release-note, approved, lgtm

#42 feat: add a blank line when adding a block element in the last line
  example/src/App.vue
  packages/editor/src/extensions/index.ts
  packages/editor/src/extensions/trailing-node/index.ts
  packages/editor/src/styles/base.scss
Labels: kind/feature, release-note, approved, lgtm

#45 feat: add node selected class name
  example/src/App.vue
  packages/editor/src/extensions/index.ts
  packages/editor/src/extensions/node-selected/index.ts
Labels: kind/feature, release-note, approved, lgtm

#40 feat: implement functionality of column cards
  example/src/App.vue
  packages/editor/src/components/bubble/BubbleMenuPlugin.ts
  packages/editor/src/extensions/columns/column.ts
  packages/editor/src/extensions/columns/columns.ts
  packages/editor/src/extensions/columns/index.ts
  packages/editor/src/extensions/indent/index.ts
  packages/editor/src/extensions/index.ts
  packages/editor/src/locales/en.yaml
  packages/editor/src/locales/zh-CN.yaml
  packages/editor/src/styles/base.scss
Labels: kind/feature, release-note, approved, lgtm

#53 pref: change the display of block-level inline elements to inline-block
  packages/editor/src/components/EditorBubbleMenu.vue
  packages/editor/src/components/bubble/BubbleItem.vue
  packages/editor/src/extensions/audio/AudioView.vue
  packages/editor/src/extensions/iframe/IframeView.vue
  packages/editor/src/extensions/image/BubbleItemImageLink.vue
  packages/editor/src/extensions/image/ImageView.vue
  packages/editor/src/extensions/link/LinkBubbleButton.vue
  packages/editor/src/extensions/video/VideoView.vue
Labels: release-note, kind/improvement, approved, lgtm

#49 feat: add supports for image with link
  packages/editor/src/extensions/image/BubbleItemImageHref.vue
  packages/editor/src/extensions/image/ImageView.vue
  packages/editor/src/extensions/image/index.ts
  packages/editor/src/locales/en.yaml
  packages/editor/src/locales/zh-CN.yaml
Labels: release-note, approved, lgtm

#48 feat: add global drag and drop function to the editor
  docs/extension.md
  docs/extension.png
  example/src/App.vue
  packages/editor/src/components/bubble/BubbleMenuPlugin.ts
  packages/editor/src/extensions/audio/index.ts
  packages/editor/src/extensions/blockquote/index.ts
  packages/editor/src/extensions/bullet-list/index.ts
  packages/editor/src/extensions/code-block/code-block.ts
  packages/editor/src/extensions/columns/columns.ts
  packages/editor/src/extensions/draggable/index.ts
  packages/editor/src/extensions/heading/index.ts
  packages/editor/src/extensions/iframe/index.ts
  packages/editor/src/extensions/image/index.ts
  packages/editor/src/extensions/index.ts
  packages/editor/src/extensions/ordered-list/index.ts
  packages/editor/src/extensions/paragraph/index.ts
  packages/editor/src/extensions/table/index.ts
  packages/editor/src/extensions/task-list/index.ts
  packages/editor/src/extensions/text/index.ts
  packages/editor/src/extensions/video/index.ts
  packages/editor/src/styles/base.scss
  packages/editor/src/styles/columns.scss
  packages/editor/src/styles/draggable.scss
  packages/editor/src/styles/index.scss
  packages/editor/src/types/index.ts
Labels: kind/feature, release-note, approved, lgtm

#56 fix: resolve the issue of incomplete coverage of text highlight
  packages/editor/src/extensions/highlight/index.ts
Labels: kind/bug, release-note, approved, lgtm

#58 fix: can not generate d.ts file after build
  packages/editor/vite.config.ts
Labels: kind/bug, release-note-none, approved, lgtm

#59 fix: resolve the issue of the editor menu changing with page scrolling
  example/src/App.vue
  package.json
  packages/editor/src/components/Editor.vue
  packages/editor/src/components/bubble/BubbleMenuPlugin.ts
  packages/editor/src/styles/base.scss
Labels: kind/bug, release-note-none, approved, lgtm
